all:
	gcc mole.c -c -Wall -Wextra
	gcc -o mole mole.c 
	gcc spiritd.c -c -Wall -Wextra
	gcc -o spiritd spiritd.c 
clean:
	rm mole
	rm mole.o 
	rm spiritd
	rm spiritd.o
mole:
	gcc mole.c -c -Wall -Wextra
	gcc -o mole mole.c 

spititd:
	gcc spiritd.c -c -Wall -Wextra
	gcc -o spiritd spiritd.c 